### ISSUE TITLE
In my OSX, there in no font "DIN Alternate Bold.ttf".

### ISSUE THREAD

**Issue by bemoregt** [TetsuakiBaba/ofxGraph#1]
Hi, @TetsuakiBaba 

In my OSX, there in no font of 

ofxGuiSetFont(ofToDataPath("ofxGraph/DIN Alternate Bold.ttf"), 10);

What font is possible for my mac osx Mojave ??

Thanks.

**Comment by TetsuakiBaba** [comment]
Please check ofxGraph/Example/bin/data/ofxGraph folder. You can find the DIN Alternate Bold.ttf in it. So, please be sure that data/ofxGraph folder exits in your own project file.

**Comment by bemoregt** [comment]
@TetsuakiBaba 

Ok, I see.

Many Thanks.

Best,
form @bemoregt .
