### ISSUE TITLE
I wonder how to get buffer sized graph data to my memory, not to csv file in runtime.

### ISSUE THREAD

**Issue by bemoregt** [TetsuakiBaba/ofxGraph#2]
Hi, @TetsuakiBaba 

I have made a webcam based realtime pixels color value graph.
I've used your ofxGraph addons for OF. Thank you for your great addons.

source : https://github.com/bemoregt/ofxROIHeartRate.git

screenshot: https://github.com/bemoregt/ofxROIHeartRate/blob/master/ofxROIHeartRate.png

Then, I wonder how to get buffer sized graph data to my memory, not to csv file in runtime.
My goal is to 1D FFT(a kind of signal processing) of the 1D signal with certain length.

How to get ?

Thanks in advance ~

Best,
@bemoregt.

**Comment by TetsuakiBaba** [comment]
Hi, @bemoregt 

Here is a basic sample to copy plotdata to your array from the graph(ofxGraph graph).

 float copydata[graph.plotdata[0].size()];
for( int i = 0; i < graph.plotdata[0].size(); i++ ){
        copydata[i] =  graph.plotdata[0][i];
}

If you wanna get plotdata from multiplot graph, graph.plotdata[ multiplot_number ][I] can access it.

**Comment by bemoregt** [comment]
@TetsuakiBaba 

Thanks a lot .

I will try that. and report.

Best,
@bemoregt .
